#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lcms2
Version  : 8
Release  : 4
URL      : https://github.com/mm2/Little-CMS/archive/lcms2.8.tar.gz
Source0  : https://github.com/mm2/Little-CMS/archive/lcms2.8.tar.gz
Summary  : LCMS Color Management Library
Group    : Development/Tools
License  : IJG MIT
Requires: lcms2-bin
Requires: lcms2-lib
Requires: lcms2-doc
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : zlib-dev

%description
Please see the documentation in doc folder

%package bin
Summary: bin components for the lcms2 package.
Group: Binaries

%description bin
bin components for the lcms2 package.


%package dev
Summary: dev components for the lcms2 package.
Group: Development
Requires: lcms2-lib
Requires: lcms2-bin
Provides: lcms2-devel

%description dev
dev components for the lcms2 package.


%package doc
Summary: doc components for the lcms2 package.
Group: Documentation

%description doc
doc components for the lcms2 package.


%package lib
Summary: lib components for the lcms2 package.
Group: Libraries

%description lib
lib components for the lcms2 package.


%prep
%setup -q -n Little-CMS-lcms2.8

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489853608
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1489853608
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jpgicc
/usr/bin/linkicc
/usr/bin/psicc
/usr/bin/transicc

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/liblcms2.so
/usr/lib64/pkgconfig/lcms2.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/liblcms2.so.2
/usr/lib64/liblcms2.so.2.0.8
